### ISSUE TITLE
请停止侵权，删除项目，谢谢

### ISSUE THREAD

**Issue by tangjinzhou** [fudiwei/x.surely-vue-table#1]
您好，
我是开源项目 Ant Design Vue 项目的作者，同时也是商业组件 @surely-vue 的作者，我们一直期望能够通过商业组件来获得一定的收入来维持整个团队的运转。
对于 @surely-vue/table 的破解严重影响了我们的收入，实际上破解后的旗舰版依然是构成侵权违法的，对于个人完全没有必要为公司节省成本承担法律风险。
如果对于个人或者无力承担费用的公司，vxe-table 也是不错的选择。

虽然你已在项目中声明(商业项目请使用正版)，但依然影响了我们项目的正常运行，也构成了侵权违法。期望尽快删除项目，及其他各平台的传播文章等。

感谢

**Comment by fudiwei** [comment]
👌
